language: node_js
node_js: node
deploy:
  provider: pages
  local_dir: dist
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: some.name@gmail.com
  name: Some Name
  on:
    branch: master
